# Generated by Django 4.2.5 on 2023-09-12 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userFolder', '0005_alter_account_email_alter_account_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
                ('resume_objective', models.CharField(max_length=255)),
                ('education_level', models.CharField(max_length=255)),
                ('name_of_institution', models.CharField(max_length=255)),
                ('year_graduated', models.CharField(max_length=255)),
                ('achievements', models.CharField(max_length=255)),
                ('languages', models.CharField(max_length=255)),
                ('hobbies_interest', models.CharField(max_length=255)),
                ('skill', models.CharField(max_length=255)),
                ('proficiency', models.CharField(max_length=255)),
                ('reward_name', models.CharField(max_length=255)),
                ('year_received', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('reward_description', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('published_year', models.CharField(max_length=255)),
                ('project_description', models.CharField(max_length=255)),
                ('reference_full_name', models.CharField(max_length=255)),
                ('relationship_to_you', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('contact_information', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userFolder.account')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('bio', models.CharField(max_length=255, null=True)),
                ('social_links', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('portfolio_link', models.CharField(max_length=255, null=True)),
                ('educational_attainment', models.CharField(max_length=255, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userFolder.account')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userFolder.account')),
            ],
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=False)),
                ('is_disliked', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekerFolder.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekerFolder.post')),
            ],
        ),
    ]
