# Generated by Django 4.2.5 on 2023-09-12 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userFolder', '0005_alter_account_email_alter_account_role'),
        ('seekerFolder', '0004_comments_created_engagement_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='account',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, to='userFolder.account'),
            preserve_default=False,
        ),
    ]
