# Generated by Django 4.2.5 on 2023-09-12 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userFolder', '0005_alter_account_email_alter_account_role'),
        ('seekerFolder', '0005_comments_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='account',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, to='userFolder.account'),
            preserve_default=False,
        ),
    ]
