# Generated by Django 4.2.5 on 2023-09-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerFolder', '0008_remove_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='custom_key',
            field=models.CharField(default='keylessnumber', max_length=30),
            preserve_default=False,
        ),
    ]
