# Generated by Django 4.2.5 on 2023-09-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerFolder', '0009_engagement_custom_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='custom_key',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
