# Generated by Django 4.2.5 on 2023-09-24 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seekerFolder', '0010_alter_engagement_custom_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='account',
        ),
        migrations.AddField(
            model_name='comments',
            name='commentor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='comments',
            name='photo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='comments',
            name='profile',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='seekerFolder.profile'),
            preserve_default=False,
        ),
    ]
