# Generated by Django 4.2.5 on 2023-10-09 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userFolder', '0005_alter_account_email_alter_account_role'),
        ('seekerFolder', '0014_alter_comments_post_alter_engagement_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='profile',
        ),
        migrations.AddField(
            model_name='engagement',
            name='engager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AllProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('social_links', models.CharField(max_length=255, null=True)),
                ('portfolio_link', models.CharField(max_length=255, null=True)),
                ('educational_attainment', models.CharField(max_length=255, null=True)),
                ('comp_name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('emp_count', models.CharField(max_length=255)),
                ('subsidiaries_count', models.CharField(max_length=255)),
                ('comp_overview', models.CharField(max_length=255)),
                ('site_link', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userFolder.account')),
            ],
        ),
    ]
