# Generated by Django 4.2.5 on 2023-10-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerFolder', '0018_alter_allprofile_bio_alter_allprofile_comp_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poster_name',
            field=models.CharField(default='Arvin Malaluan', max_length=100),
            preserve_default=False,
        ),
    ]
