# Generated by Django 4.2.5 on 2023-10-10 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seekerFolder', '0019_post_poster_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(
                default="2", on_delete=django.db.models.deletion.CASCADE, to='seekerFolder.allprofile'),
            preserve_default=False,
        ),
    ]
