# Generated by Django 4.2.5 on 2023-10-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerFolder', '0020_post_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='poster_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
