# Generated by Django 4.2.5 on 2023-10-10 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userFolder', '0005_alter_account_email_alter_account_role'),
        ('seekerFolder', '0021_alter_post_poster_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='allprofile',
            name='account',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='userFolder.account'),
        ),
    ]
