# Generated by Django 4.2.5 on 2023-10-10 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seekerFolder', '0023_remove_post_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='account',
        ),
    ]
