# Generated by Django 4.2.5 on 2023-10-10 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seekerFolder', '0024_remove_engagement_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='account',
        ),
    ]
