# Generated by Django 4.2.5 on 2023-10-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerFolder', '0025_remove_comments_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commentor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='photo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
