# Generated by Django 4.2.5 on 2023-10-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerFolder', '0026_alter_comments_commentor_alter_comments_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allprofile',
            name='comp_name',
        ),
        migrations.AlterField(
            model_name='allprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
