# Generated by Django 4.2.5 on 2023-10-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerFolder', '0027_remove_allprofile_comp_name_alter_allprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allprofile',
            name='account',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
