# Generated by Django 4.2.5 on 2023-10-15 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userFolder', '0005_alter_account_email_alter_account_role'),
        ('seekerFolder', '0028_alter_allprofile_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='allprofile',
            name='fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userFolder.account'),
        ),
    ]
