# Generated by Django 4.2.5 on 2023-10-16 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userFolder', '0005_alter_account_email_alter_account_role'),
        ('seekerFolder', '0029_allprofile_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allprofile',
            name='fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allprofile', to='userFolder.account'),
        ),
    ]
