# Generated by Django 4.2.5 on 2023-10-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerFolder', '0030_alter_allprofile_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
