# Generated by Django 4.2.5 on 2023-10-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerFolder', '0034_alter_post_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='compatibility',
            field=models.TextField(blank=True, null=True),
        ),
    ]
