# Generated by Django 4.2.5 on 2023-11-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerFolder', '0035_resume_compatibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_objective',
            field=models.TextField(),
        ),
    ]
