# Generated by Django 4.2.5 on 2023-09-30 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userFolder', '0005_alter_account_email_alter_account_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_key', models.CharField(max_length=20)),
                ('involve_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_one', to='userFolder.account')),
                ('involve_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_two', to='userFolder.account')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.TextField()),
                ('message_created', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.conversation')),
            ],
        ),
    ]
