# Generated by Django 4.2.5 on 2023-10-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_messages_custom_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='id',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='custom_key',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
