# Generated by Django 4.2.5 on 2023-10-01 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_conversation_custom_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='custom_key',
            new_name='reciever',
        ),
    ]
