# Generated by Django 4.2.5 on 2023-10-01 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_rename_custom_key_messages_reciever'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='message_content',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
