# Generated by Django 4.2.5 on 2023-10-11 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seekerFolder', '0028_alter_allprofile_account'),
        ('chat', '0008_rename_message_content_messages_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='involve_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_one', to='seekerFolder.allprofile'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='involve_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_two', to='seekerFolder.allprofile'),
        ),
    ]
