# Generated by Django 4.2.5 on 2023-10-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_conversation_name_conversation_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='involve_one',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='involve_two',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
