# Generated by Django 4.2.5 on 2023-10-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_rename_name_conversation_involve_one_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
