# Generated by Django 4.2.5 on 2023-09-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userFolder', '0002_account_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
