# Generated by Django 4.2.5 on 2023-09-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userFolder', '0003_alter_account_email_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
