# Generated by Django 4.2.5 on 2023-10-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userFolder', '0006_alter_account_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(
                default='allowed', max_length=100, null=True),
        ),
    ]
