# Generated by Django 4.2.5 on 2023-10-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userFolder', '0007_alter_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(blank=True, default='allowed', max_length=100, null=True),
        ),
    ]
