# Generated by Django 4.2.5 on 2023-09-15 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userFolder', '0005_alter_account_email_alter_account_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('emp_count', models.CharField(max_length=255)),
                ('subsidiaries_count', models.CharField(max_length=255)),
                ('comp_overview', models.CharField(max_length=255)),
                ('site_link', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userFolder.account')),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('emp_type', models.CharField(max_length=255)),
                ('req_expi', models.CharField(max_length=255)),
                ('req_educ', models.CharField(max_length=255)),
                ('job_desc', models.TextField()),
                ('contact_info', models.CharField(max_length=255)),
                ('app_duedate', models.CharField(max_length=255)),
                ('qualifications', models.TextField()),
                ('responsibilities', models.TextField()),
                ('benefits', models.TextField()),
                ('salary', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.recruiterprofile')),
            ],
        ),
    ]
