# Generated by Django 4.2.5 on 2023-10-14 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seekerFolder', '0028_alter_allprofile_account'),
        ('recruiter', '0002_remove_jobpost_profile_jobpost_allprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='allprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_poster', to='seekerFolder.allprofile'),
        ),
    ]
