# Generated by Django 4.2.5 on 2023-10-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0005_alter_jobpost_app_duedate_alter_jobpost_benefits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
