# Generated by Django 4.2.5 on 2023-10-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0006_jobpost_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
