# Generated by Django 4.2.5 on 2023-10-15 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seekerFolder', '0029_allprofile_fk'),
        ('recruiter', '0007_jobpost_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='applicant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_profile', to='seekerFolder.allprofile'),
        ),
    ]
