# Generated by Django 4.2.5 on 2023-10-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0010_alter_applicants_job_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants',
            name='applicant_id',
        ),
        migrations.AddField(
            model_name='applicants',
            name='applicount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
