# Generated by Django 4.2.5 on 2023-10-15 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seekerFolder', '0029_allprofile_fk'),
        ('recruiter', '0011_remove_applicants_applicant_id_applicants_applicount'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seekerFolder.allprofile'),
        ),
    ]
