# Generated by Django 4.2.5 on 2023-10-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0012_applicants_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants',
            name='applicount',
        ),
    ]
