# Generated by Django 4.2.5 on 2023-10-15 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0014_rename_job_id_applicants_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='applied',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='recruiter.jobpost'),
        ),
    ]
