# Generated by Django 4.2.5 on 2023-10-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0015_applicants_applied_alter_applicants_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='custom_key',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
