# Generated by Django 4.2.5 on 2023-10-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0017_alter_applicants_custom_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='sched',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
