# Generated by Django 4.2.5 on 2023-10-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0018_applicants_sched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
