# Generated by Django 4.2.5 on 2023-10-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0019_alter_jobpost_contact_info_alter_jobpost_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
