# Generated by Django 4.2.5 on 2023-10-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0020_applicants_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='custom_key',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
