# Generated by Django 4.2.5 on 2023-10-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0023_alter_applicants_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='salary',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='skills',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
