# Generated by Django 4.2.5 on 2023-11-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0026_applicants_hire_applicants_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='compatibility',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
