# Generated by Django 4.2.5 on 2023-11-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0027_applicants_compatibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='hire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='interview',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
