# Generated by Django 4.2.5 on 2023-11-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0028_alter_applicants_hire_alter_applicants_interview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants',
            name='sched',
        ),
        migrations.AlterField(
            model_name='applicants',
            name='applied',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
